### ISSUE TITLE
User Auth MVP

### ISSUE THREAD

**Issue by AdamYLiang** [vineethsomanchi/VinFlix#2]
- [x] After signing in the app seems to crash. The error seems to be a routing issue where it is rendering the same view in a circular fashion. 
- [x] `Demo user` should be functional. 

Let me know if you have any questions on these.

**Comment by AdamYLiang** [comment]
- [ ] If the user is logged in the splash page should not be accessible. 

**CSS**
- [ ] Form input fields should be a bit closer together. 
- [ ] Fix the onHover, consider using a `placeholder` text for now. 
- [ ] Errors for session form should appear underneath the respective field like the original app. 

Let me know if you have any questions!

**Comment by vineethsomanchi** [comment]
> * [x]  After signing in the app seems to crash. The error seems to be a routing issue where it is rendering the same view in a circular fashion.
> * [x]  `Demo user` should be functional.
> 
> Let me know if you have any questions on these.
